"""Adicionado Soft Delete aos produtos

Revision ID: 798344d3da39
Revises: 7cb159417211
Create Date: 2026-04-20 10:37:44.620657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798344d3da39'
down_revision = '7cb159417211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos_estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos_estoque', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
