"""Migração inicial: Estoque, Pulverização e Alertas

Revision ID: 7cb159417211
Revises: 
Create Date: 2026-04-20 10:37:09.299227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7cb159417211'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pulverizacoes')
    with op.batch_alter_table('cronograma_pulverizacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produtor_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('titulo', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('data_planejada', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('atualizado_em', sa.DateTime(), nullable=True))
        batch_op.alter_column('lavoura_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('descricao',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'produtores', ['produtor_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.drop_column('data_prevista')

    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produtor_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('numero_nf', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('data_movimentacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=True))
        batch_op.alter_column('produto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.create_foreign_key(None, 'produtores', ['produtor_id'], ['id'])
        batch_op.drop_column('data')

    with op.batch_alter_table('produtos_estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_interno', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('unidade_medida_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('quantidade_minima', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('quantidade_maxima', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('descricao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fornecedor', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('atualizado_em', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['codigo_interno'])
        batch_op.drop_constraint(batch_op.f('produtos_estoque_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categorias_estoque', ['categoria_id'], ['id'])
        batch_op.create_foreign_key(None, 'unidades_medida', ['unidade_medida_id'], ['id'])
        batch_op.drop_column('usuario_id')
        batch_op.drop_column('quantidade_atual')
        batch_op.drop_column('categoria')
        batch_op.drop_column('unidade_medida')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos_estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_medida', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('categoria', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('quantidade_atual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('produtos_estoque_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('atualizado_em')
        batch_op.drop_column('ativo')
        batch_op.drop_column('fornecedor')
        batch_op.drop_column('descricao')
        batch_op.drop_column('quantidade_maxima')
        batch_op.drop_column('quantidade_minima')
        batch_op.drop_column('unidade_medida_id')
        batch_op.drop_column('categoria_id')
        batch_op.drop_column('codigo_interno')

    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('produto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('criado_em')
        batch_op.drop_column('data_movimentacao')
        batch_op.drop_column('numero_nf')
        batch_op.drop_column('produtor_id')

    with op.batch_alter_table('cronograma_pulverizacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_prevista', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('descricao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('lavoura_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('atualizado_em')
        batch_op.drop_column('criado_em')
        batch_op.drop_column('observacoes')
        batch_op.drop_column('data_planejada')
        batch_op.drop_column('titulo')
        batch_op.drop_column('usuario_id')
        batch_op.drop_column('produtor_id')

    op.create_table('pulverizacoes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lavoura_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_aplicacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('produto_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dose_por_ha', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume_calda', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('clima_condicao', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('responsavel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lavoura_id'], ['lavouras.id'], name=op.f('pulverizacoes_lavoura_id_fkey')),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos_estoque.id'], name=op.f('pulverizacoes_produto_id_fkey')),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], name=op.f('pulverizacoes_responsavel_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pulverizacoes_pkey'))
    )
    # ### end Alembic commands ###
